module.exports = {
productsHome: '//*[@id="header"]/div/div/div/div[2]/div/ul/li[2]/a',
addToCartBtnFirst: '/html/body/section[2]/div[1]/div/div[2]/div/div[2]/div/div[1]/div[1]/a',
continueShoppingBtn: '//*[@id="cartModal"]/div/div/div[3]/button',
addToCartBtnSecond:"/html/body/section[2]/div[1]/div/div[2]/div/div[5]/div/div[1]/div[2]/div/a",
viewCart: '//*[@id="cartModal"]/div/div/div[2]/p[2]/a',
SuccessfullAddCart: '//*[@id="cartModal"]/div/div/div[2]/p[1]',
proceedBtn: '//*[@id="do_action"]/div[1]/div/div/a',
addressDetails: '//*[@id="cart_items"]/div/div[2]/h2',
YourDeliveryAddress: '//*[@id="address_delivery"]/li[1]/h3',
YourBillingAddress: '//*[@id="address_invoice"]/li[1]/h3',
addComment: '//*[@id="ordermsg"]/textarea',
placeOrderBtn: '//*[@id="cart_items"]/div/div[7]/a',
payment: '//*[@id="cart_items"]/div/div[2]/h2',
nameOnCard: '//*[@id="payment-form"]/div[1]/div/input',
cardNumber: '//*[@id="payment-form"]/div[2]/div/input',
CVC: '//*[@id="payment-form"]/div[3]/div[1]/input',
expiration: '//*[@id="payment-form"]/div[3]/div[2]/input',
YYYY: '//*[@id="payment-form"]/div[3]/div[3]/input',
confirmOrderBtn: '//*[@id="submit"]',
successfullPayment: '//*[@id="success_message"]/div',
congratulationsMsg: '//*[@id="form"]/div/div/div/p',
  };
